// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCSNGSOw2eazjZPRPqY7jIMSZ0zwu8NgE',
    appId: '1:969857981323:web:a36228af377f3e9b66ad8e',
    messagingSenderId: '969857981323',
    projectId: 'shinda-app',
    authDomain: 'shinda-app.firebaseapp.com',
    storageBucket: 'shinda-app.appspot.com',
    measurementId: 'G-FSFECYC0CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1q_5bl5VPjGr5QQzt3COqFjzSxI2FCEg',
    appId: '1:969857981323:android:7812189ed2360f3e66ad8e',
    messagingSenderId: '969857981323',
    projectId: 'shinda-app',
    storageBucket: 'shinda-app.appspot.com',
  );
}
